---
title: "Earth System Evolution"
author: "Earth System Crew"
---

## Motivation
Earth scientists increasingly recognize the need to study not only the components of the Earth system (lithosphere-hydrosphere-atmosphere-biosphere), but also the complex and evolving nature of their coupling. Understanding these interconnections is crucial for global environmental projections, including climate tipping points, ocean acidification, sea level rise, biodiversity loss and mass extinctions. Although unprecedented in the history of human civilization, such dramatic upheavals have occurred repeatedly throughout Earth's history. Researchers therefore turn to the geological record for insights into causes, consequences, and time scales of global change in the past.

### Goals
The Earth System Evolution group seeks new fundamental insights into the coupling between Earth system components across time scales. We develop and test data-driven techniques for quantifying complex interactions directly from observations, and apply these methods to geological records of Earth system history on time scales ranging from thousands to hundreds of millions of years.


Feel free to have a look at our <a href="/project/">ongoing projects</a> and <a href="/publication/">recent publications</a>.
