baseurl = "https://engraver-boar-33446.netlify.com/"
relativeurls = true
title = "Earth System Evolution"
theme = "ghostwriter"
languageCode = "en-us"

[Author]
    name = "Kristian Agasøster Haaga"
    profile = ""

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Earth System Evolution"
    description = ""
    github = ""
    gitlab = ""
    linkedin = ""
    gplus = ""
    twitter = ""
    stackoverflow = ""
    email = ""
    opengraph = false
    shareTwitter = false
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Monday, January 2, 2006"
    showRecentPostsOnMain = true

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Front"
    url = "/"
    weight = 1
    
[[menu.main]]
    name = "Research"
    url = "/page/research/"
    weight = 1
    
[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2
    
[[menu.main]]
    name = "Publications & Talks"
    url = "/publication/"
    weight = 3

[[menu.main]]
    name = "Recent activity"
    url = "/post/"
    weight = 4
    
[[menu.main]]
    name = "The crew"
    url = "/page/crew/"
    weight = 5