---
title: "Phanerozoic Earth system evolution and marine biodiversity"
description: "Hannisdal B, Peters SE (2011). Science 334: 1121-1124."
date: "2011-11-25"
---

The Phanerozoic fossil record of marine animal diversity covaries with the amount of marine sedimentary rock. The extent to which this covariation reflects a geologically controlled sampling bias remains unknown. We show that Phanerozoic records of seawater chemistry and continental flooding contain information on the diversity of marine animals that is independent of sedimentary rock quantity and sampling. Interrelationships among variables suggest long-term interactions among continental flooding, sulfur and carbon cycling, and macroevolution. Thus, mutual responses to interacting Earth systems, not sampling biases, explain much of the observed covariation between Phanerozoic patterns of sedimentation and fossil biodiversity. Linkages between biodiversity and environmental records likely reflect complex biotic responses to changing ocean redox conditions and long-term sea-level fluctuations driven by plate tectonics.

Pdf versions of the <a href="http://science.sciencemag.org/content/sci/334/6059/1121.full.pdf">paper</a> and <a href="http://science.sciencemag.org/content/sci/suppl/2011/11/23/334.6059.1121.DC1/Hannisdal.SOM.pdf">supplementary materials</a>. 

James Crampton also published a <a href="http://www.sciencemag.org/content/334/6059/1073.summary">perspective</a> on the paper.