---
title: "3. Energy landscapes and microbial interactions in hydrothermal systems"
description: "The influence of energy availability on microbial interactions in hydrothermal systems"
author: "Earth System Crew"
output: blogdown::html_page
---

## Project 3: Energy landscapes.

### Motivation 

Hydrothermal vents support unique microbial communities which, unlike photosynthetic organisms, gain their metabolic energy from inorganic chemical reactions. Numerical models have been used to explore microbial composition and interactions in these systems by determining how much energy obtained from chemical reactions is converted to produce new biomass. 

In this project, we want to build up a model that considers both energy availability and population dynamics in order to have an insight on how microbial communities are shaped in these ecosystems. Models become a powerful predictive tool in these type of studies given the difficulties that arise during *in situ* sampling and can help to solve questions about how the proportion of microbial metabolisms found in these systems vary, the distribution in different microbial habitats, and the impact of microorganisms on the composition of hydrothermal fluids. In addition to this, a step further will be taken in the project by implementing an inverse model, which will help to estimate the values of unmeasurable model parameters (or flows) and parameter uncertainties. An inverse model is appropriate for this type of system, as is not easily accessible or observable the quantification of the energy available nor the amount of organisms in hydrothermal vents.